name: fedsense
services:
  # Frontend Service  
  - name: frontend
    source_dir: frontend
    github:
      repo: RohanSriram19/FedSense
      branch: main
    run_command: npm start
    build_command: npm ci && npm run build
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
    health_check:
      http_path: /api/health

  # Backend Service
  - name: backend
    dockerfile_path: Dockerfile.backend
    github:
      repo: RohanSriram19/FedSense  
      branch: main
    instance_count: 1
    instance_size_slug: basic-xs
    routes:
      - path: /api
    envs:
      - key: ENV
        value: production
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
    health_check:
      http_path: /health

# Database
databases:
  - name: db
    engine: PG
    num_nodes: 1
    size: db-s-dev-database
    version: "14"
