version: '3.8'

services:
  mlflow:
    image: python:3.11-slim
    container_name: fedsense_mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow
      - ./artifacts:/mlflow/artifacts
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow/mlflow.db
      - MLFLOW_ARTIFACTS_DESTINATION=/mlflow/artifacts
    command: >
      bash -c "
        pip install mlflow>=2.8.0 &&
        mlflow server 
          --host 0.0.0.0 
          --port 5000 
          --backend-store-uri sqlite:///mlflow/mlflow.db 
          --default-artifact-root /mlflow/artifacts 
          --serve-artifacts
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mlflow_data:
    driver: local
